### ISSUE TITLE
e_shortcode error!

### ISSUE THREAD

**Issue by parsfounder** [e107inc/pdf#4]
Database Utilities >> Plugin View and Scan
![Screenshot](https://user-images.githubusercontent.com/10089685/107844778-b832a100-6deb-11eb-8103-04ed8aca3da2.png)

**Comment by parsfounder** [comment]
Removing the close PHP tag ?> at the end of e_shortcode.php and scanning again solved the issue.

**Comment by Moc** [comment]
Reopened because this has to be fixed.
